name: Lint

on:
  push:
    branches: [main]
  pull_request:
    types: [opened, synchronize]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Run lint
        run: ./gradlew lint

      - uses: actions/upload-artifact@v4
        with:
          name: lint-results-debug.html.zip
          path: app/build/reports/lint-results-debug.html