name: Build

on:
  push:
    branches: [main]
  pull_request:
    types: [opened, synchronize]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Build App
        run: ./gradlew :app:assembleDebug

      - uses: actions/upload-artifact@v4
        with:
          name: app-debug.apk.zip
          path: app/build/outputs/apk/debug/app-debug.apk